sudo: false
cache:
  directories:
  - $HOME/.m2
language: android
jdk: oraclejdk8
android:
  components:
    - android-22
    - build-tools-22.0.0
    - sys-img-armeabi-v7a-android-22
  licenses:
    - android-sdk-license-5be876d5
env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a AVD_NAME=Default

before_script:
  - echo no | android create avd --force -n $AVD_NAME -t $ANDROID_TARGET --abi $ANDROID_ABI
  
script: mvn clean install -Dfull-integration-test=true -X

