language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a AVD_NAME=Default

before_script:
  - echo no | android create avd --force -n $AVD_NAME -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd $AVD_NAME -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
  
script: mvn clean install -Pinstall-appium,use-installed-appium,start-and-stop-emulator,integration-test

